### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by larsemil** [poweradmin/poweradmin#183]
Is there LDAP Auth builtin. And if - where is it documented?

**Comment by maul123** [comment]
help me, why wrong? i need add new user, sorry for my bad english hehe
![why](https://cloud.githubusercontent.com/assets/13130399/8448766/ac81c7d8-1ffd-11e5-97cb-1786abae1a1b.PNG)

**Comment by edmondas** [comment]
@maul123 - which version you're using? I cannot reproduce this on master (latest code).

**Comment by maul123** [comment]
poweradmin v 2.1.7

**Comment by maul123** [comment]
whether poweradmin could be used as filtering dns? sorry i am newbie

**Comment by edmondas** [comment]
Not sure what kind of filtering do you need, but Poweradmin has no such functionality.

If you DNS server is required only for recursive requests then take a look to PowerDNS recursor which has filtering capability:
https://scriptthe.net/2015/03/09/handy-dns-response-filtering-with-pdns-recursor/

Otherwise you need to look to these PowerDNS features:
https://doc.powerdns.com/md/authoritative/backend-pipe/
https://doc.powerdns.com/md/authoritative/backend-lua/

**Comment by maul123** [comment]
thak you edmondas

**Comment by SebTM** [comment]
As poweradmin supports LDAP in current master (and future 2.1.8) and @maul123 questions seems to be solved I will close this issue.

**Comment by nonbinary** [comment]
I'm with larsemil on the groups settings.
I've got LDAP integrated on most logins in my organization, and everything is controlled in the database, using group memberships. It is basically poweradmin and one other part where I need to log in to another place, and add/remove users. All other integration is groups-based. As far as I understand, this is the standardized way of doing it. Pull users from the database, but have an (optional) required group field. Don't require local users in Poweradmin.
Doing it this way is a security issue in a large organization, as it increases the risk for human errors.
