### ISSUE TITLE
the column content from table records has to be changed from VARCHAR(255) to TEXT to enable DKIM Signatures with 4096 bit

### ISSUE THREAD

**Issue by jmboettger** [poweradmin/poweradmin#192]

**Comment by clovis818** [comment]
I agree

**Comment by SebTM** [comment]
This table is not provided by poweradmin, it's from the PowerDNS schema. Since the documentation tells us to create content as "VARCHAR(64000)" field it gets automatically converted to a "mediumtext".

This happens in cause of the utf8 usage. (http://stackoverflow.com/questions/7619846/why-if-i-create-a-varchar65535-i-get-a-mediumtext)

So for mysql it should be "self-solved" for now? Can someone provide additional informations for the other backends supported by poweradmin?

**Comment by edmondas** [comment]
It's related to PowerDNS, as mentioned above. The latest MySQL schema can be found here https://raw.githubusercontent.com/PowerDNS/pdns/rel/auth-4.5.x/modules/gmysqlbackend/schema.mysql.sql

**Comment by rroethof** [comment]
I would advise to update:

git diff templates/edit_zone_templ.html
diff --git a/templates/edit_zone_templ.html b/templates/edit_zone_templ.html
index 5ebf8d72..a0015cf5 100644
--- a/templates/edit_zone_templ.html
+++ b/templates/edit_zone_templ.html
@@ -37,7 +37,8 @@
         <tr>
             <td class="col-sm-2">{{record['name']}}</td>
             <td class="col-sm-1">{{record['type']}}</td>
-            <td class="col-sm-3">{{record['content']}}</td>
+            <td class="col-sm-3">
+<input class="form-control form-control-sm" type="text" name="content" value="{{record['content']}}" disabled></td>
             {% if (record['type'] == "MX") or (record['type'] == "SRV") %}
             <td class="col-sm-1">{{record['prio']}}</td>
             {% else %}

**Comment by edmondas** [comment]
@rroethof The UI has been tweaked based on your suggestions.
