### ISSUE TITLE
Error: Failed to get DNSSEC key details

### ISSUE THREAD

**Issue by bjo81** [poweradmin/poweradmin#222]
Hi,
I upgraded poweradmin to 2.1.7 and Powerdns to 3.4.1 running on Debian Wheezy. I enabled "pdnssec_use" and rectified all zones via pdnssec. But I get "Error: Failed to get DNSSEC key details" for all domains, also updated to 2.1.8. did not help. Setting display_errors=on in php.ini didn't bring any useful information which sql-queries fail.

**Comment by bjo81** [comment]
I've put now 'var_dump($command); var_dump($output); var_dump($return_code);' in dnssec_call_pdnssec after the exec statement:
/usr/bin/pdnssec show-zone myzone.tld" array(0) { } int(1)

**Comment by bjo81** [comment]
Fixed. Add user www-data to pdns, chgrp pdns on PowerDNS-configs.

**Comment by bytesplit** [comment]
Thanks for the hint. The error message in the log is not directly hitting me into checking the configs permissions.

**Comment by glardone** [comment]
@bjo81 I am trying to use DNSSEC with Poweradmin, but I do not understand how to solve the error
Error: Failed to get DNSSEC key details.
I have already added the user www-data to pdns group and changed the group of config.inc.php to pdns: I missed something?
Thank you!

**Comment by dmorley** [comment]
Having zero luck trying to fix this also, any help would be great!

**Comment by dmorley** [comment]
Ah I got it figured out from https://github.com/poweradmin/poweradmin/issues/96#issuecomment-87592982 @glardone if you still need it check your permissions on /etc/powerdns. Make sure www-data can see them all.

**Comment by glardone** [comment]
Hi,
I have installed a new Debian 8 test server with PowerDNS 4.0.3 and DNSSEC active.
In the configuration file /inc/config.inc.php I have modified:
`"$pdnssec_command = '/usr/bin/pdnssec';"`
to
`$pdnssec_command = '/usr/bin/pdnsutil';`

In the file /etc/powerdns/pdns.conf I put in it all configurations, in such a way as to have a single configuration file for PowerDNS.

Then I added the user www-data to read this file:
` setfacl -m u:www-data:r /etc/powerdns/pdns.conf`
and this directory:
` setfacl -m u:www-data:r /usr/bin/pdnsutil`

These devices now avoid the mistakes on permissions that occurred before:
```
Warning: unable to read configuration file '/etc/powerdns/pdns.conf'.
Error: No database backends configured for launch, unable to function
```
However, there are still other errors from dnssec.php:
Error: Failed to call pdnssec utility.
Error: Failed to get DNSSEC key details.

And in error.log of Apache:
```
PHP Notice:  Undefined variable: perm_meta_edit in /var/www/poweradmin/dnssec.php on line 53, referer: http://localhost/edit.php?name=my.domains&id=1
PHP Notice:  Undefined variable: perm_meta_edit in /var/www/poweradmin/dnssec.php on line 53, referer: http://localhost/edit.php?name=my.domains&id=1
PHP Notice:  Undefined variable: perm_view in /var/www/poweradmin/dnssec.php on line 61, referer: http://localhost/edit.php?name=my.domains&id=1
PHP Notice:  Undefined variable: perm_view in /var/www/poweradmin/dnssec.php on line 61, referer: http://localhost/edit.php?name=my.domains&id=1
PHP Warning:  Invalid argument supplied for foreach() in /var/www/poweradmin/dnssec.php on line 94, referer: http://localhost/edit.php?name=my.domains&id=1
```
You have ideas?
Thank you!

**Comment by danfratamico** [comment]
Glardone, have you ever figured out your issue? I am running into the same exact thing...

**Comment by bynicolas** [comment]
I managed to make DNSSEC work with poweradmin. But it still needs a few fixes.

For instance, powerdns doesn't create a KSK and a DSK anymore. It creates a unique key upon securing a domain. So Poweradmin should not enable adding new keys to a domain as it is not supported anymore ( at least from what I understand ). If you try to do so, you will find Poweradmin complaining about things.

Also, you can't deactivate a key. I don't know if this is still supported as I have not checked in the docs for that.

so 3fb893580e588d3bfb1bfba09b748615b50fb34b and fac25d9aa378e2b2a7842fc41c3ff2dde0ccd282 should make managing DNSSEC a possibility, but keep those caveats in mind.

@glardone, your `Error: Failed to call pdnssec utility.` error is because you make `/usr/bin/pdnsutil` readable but not **executable**.  Try `setfacl -m u:www-data:x /usr/bin/pdnsutil`, it should work.

Your other error was because the `$keys` array wasn't containing the right values since it was based on version 3.4 of pdns.  my commits should take care of that.  the apache warning are also fixed by those commits.
