### ISSUE TITLE
Templates causing duplicate records

### ISSUE THREAD

**Issue by plushcthulhu** [poweradmin/poweradmin#231]
Just finished a server migration and installed Poweradmin 2.1.7. I noticed that when a zone is assigned a different template, the records for this new template are ADDED to the already existing records.

In 2.1.6, when selecting a different template, the existing records were overwritten.
Is this new behaviour? Or has something gone wrong with my migration?

**Comment by edmondas** [comment]
This could be related changes made to fix #63.

**Comment by sorinpohontu** [comment]
Confirmed on 2.7.1 on PowerDNS 2.9.22.
Changing template for a zone keeps old and adds records from the new template.

**Comment by SebTM** [comment]
As I don't use zone templates I'm not quite sure which behavior is excepted and must useful. From safety view it would be need a security check before clearing old data when changing template.

What needs to be checked:

1. Create a new zone without template containing some records - also one existing in a template
2. Update zone to use template
3. Check if records from the template are duplicates or updated

If duplicates we need to check before create to trigger update instated of creating them.

**Comment by andi-blafasl** [comment]
I just installed the lasted poweradmin from github and experienced the same problem with duplicated records if the template is changed.
The biggest problem is: The SOA record gets duplicated too! And you can not remove one of the SOA records because poweradmin is preventing this.
As a workaround you can change the record type from SOA to TXT and then delete this record. Ugly but working ;-)

**Comment by ReArmedHalo** [comment]
The biggest issue with ADDING to exist is the fact that you get duplicate SOA records, which require you going into the backend (MariaDB server in my case) and deleting the old SOA record as PowerAdmin won't let you.

**Comment by Frank071** [comment]
@SebTM I don't know if you have the information requested on Mar 7 yet, but I can confirm that the behaviour now is that the records are duplicated in stead of updated or removed. They get new ids and everything. And as said by others: you are then equipped with 2 SOA records that you can not remove in a straightforward way.
If you need additional info: just say so

**Comment by SebTM** [comment]
I've created a "quick fix" for it and pushed it to the current master. You should use it without updating to the current master-branch, as I think it is not stable for use! Just check the commit referenced over this comment and change/add the lines. (2 lines changed only)

**WARNING: This will also change the "logical behaviour! Now, Poweradmin will delete all records of the zone which got created in relation to a template. If the template have a SOA-Record the old SOA-Record will be delete automatically - it dosn't matter if it comes from another template or got created manually.**

At this time - it's not possible to overwrite records from a template so that they stay even if you update all domains from the template-page.
