### ISSUE TITLE
list_zones.php fails with more than 50 Zones - [HY000]: General error: 1 no such function: REGEXP - Poweradmin 2.1.8 with SQLITE backend

### ISSUE THREAD

**Issue by scarab3** [poweradmin/poweradmin#251]
Hello, 
I installed poweradmin 2.1.8 wich seems to work on Ubuntu 14.04
But list_zones.php fails when I start adding the 51st zone this page shows the error:

Show zones beginning with:
An error occurred while executing the SQL statement. Please contact an Administrator and report the problem.
The following query generated an error:

SELECT
			domains.id AS domain_id,

			zones.owner,

			domains.name AS domainname
			
FROM domains
			
LEFT 
JOIN zones
 ON domains.id=zones.domain_id
			
WHERE substring(domains.name,
1,
1) REGEXP '^[[:digit:]]' 
LIMIT 1

SQLSTATE[HY000]: General error: 1 no such function: REGEXP

From logs:

[* SQL ERROR MESSAGE FOLLOWS:\n
#0 /var/www/html/poweradmin/inc/PDOCommon.class.php(160):
PDO->query('SELECT????domai...')\n
#1 /var/www/html/poweradmin/inc/PDOLayer.php(133):
PDOCommon->query('SELECT????domai...')\n
#2 /var/www/html/poweradmin/inc/PDOCommon.class.php(211):
PDOLayer->query('SELECT????domai...')\n
#3 /var/www/html/poweradmin/inc/toolkit.inc.php(428): PDOCommon->queryOne('SELECT????domai...')\n
#4 /var/www/html/poweradmin/inc/toolkit.inc.php(379): zone_letter_start('[[:digit:]]', true)\n
#5 /var/www/html/poweradmin/list_zones.php(89): show_letters('a')\n
#6 {main}\n
SQLSTATE[HY000]: General error: 1 no such function: REGEXP\n
Full SQL Statement:SELECT\n
\t\t\tdomains.id AS domain_id,\
\t\t\tzones.owner,\n
\t\t\tdomains.name AS domainname\n
\t\t\tFROM domains\n
\t\t\tLEFT JOIN zones ON domains.id=zones.domain_id\n
\t\t\tWHERE substring(domains.name,1,1) REGEXP '^[[:digit:]]' LIMIT 1\n
*], referer: http://dns1.mycorp.com/poweradmin/bulk_registration.php

**Comment by scarab3** [comment]
The problem is related to  list_zones.php, I can find and edit domains from search.php

**Comment by scarab3** [comment]
PROBLEM: SLQITE3 doesn't accept REGEXP function used in query
WORKAROUND: changed variable iface_rowamount value in config-me.inc.php:

   $iface_rowamount = 10000; 

Please could you kindly check the query?
Thanx

**Comment by ktims** [comment]
There are a couple ways to attack this. sqlite3 does support REGEXP operator, but requires a user function to implement it. This can be done with `PDO::sqliteCreateFunction`, but is perhaps nonstandard.

sqlite3 also has a GLOB operator built-in that can be used in this case to replace regexp: "WHERE domains.name GLOB '[0-9]*").

Finally, IN could be used instead: "WHERE substr(domains.name,1,1) IN ('0','1','2','3','4','5','6','7','8','9','0').

Any of these solutions require a workaround for sqlite3 using 'substr' instead of 'substring'. My suspicion is that the 3rd option will be most efficient and is closest to standard SQL. I will look at submitting a pull request for this.

**Comment by ktims** [comment]
It isn't generalizable but the fastest way by a fairly wide margin is to use comparisons, e.g. 'WHERE domains.name BETWEEN '0' and '9zzzzzzzzzzzzzzzzz' or similar, as it can leverage the index we already have. With 'reasonable' amount of domains though it doesn't make too much difference.

I will opt for a patch using the GLOB mechanism with sqlite as it should require the least refactoring.

Postgres and sqlite are both fairly substantially faster without the substring() call and MySQL is only slightly slower so that will be removed as it is superfluous to the RE/glob. Pull request incoming shortly.

**Comment by ktims** [comment]
Please test the pull request, I don't have a live SQLite instance to use to test.

**Comment by scarab3** [comment]
Great! Thank you Ktims,
I modified inc/record.inc.php and inc/toolkit.inc.php with your patches  https://github.com/poweradmin/poweradmin/pull/253/files
and now it works.
The lists are perfect, Show zones beginning with: and also show page works with the value $iface_rowamount = N if I adjust it in inc/ config-me.inc.php

**Comment by scarab3** [comment]
I suspect the SQLITE support is partial, please see the issue #252 and #254

**Comment by scarab3** [comment]
found another problem but this bug is Fixed, thank you Ktims
