### ISSUE TITLE
poweradmin project dead?

### ISSUE THREAD

**Issue by Nurlan199206** [poweradmin/poweradmin#347]
Subj question

**Comment by danfratamico** [comment]
Same question, I hope it's not dead.

**Comment by K0HAX** [comment]
+1, same question

**Comment by Wouter0100** [comment]
Seems to be dead since 2018. I guess someone could fork and continue? :)

**Comment by yctn** [comment]
Same question, I hope it's not dead.

**Comment by prupert** [comment]
See https://github.com/PowerDNS/pdns/wiki/WebFrontends for (pretty good) alternatives.

**Comment by fenice2** [comment]
I was using this project's software for a long time but since mid 2017 I've encountered more problems with it, luckily the links in the post above provide some good software that is being updated.

I've been using https://github.com/ngoduykhanh/PowerDNS-Admin for a while now and it works well. The project also suffered from stagnation and was forked, I never managed to get the original project to install and work but the fork did, go figure. The original developer has resurrected the project and it's now under active development and, as I mentioned earlier, that now works very well in my environment.

**Comment by kiwichrish** [comment]
Just noticed this issue after posting a new one.. :-)  Lots of folks have forked it but no response from project owner of poweradmin which is a shame..  I use it on a couple of sites and although the UI is a bit dated it's good for what I need.

**Comment by Morgon** [comment]
I came to find this answer, as well; commits are clearly being accepted, several this year, but the last actual release was in 2014.

**Comment by fenice2** [comment]
It's really not much use accepting commits if there's no actual product being released. While I found this project relatively easy to use there are some continuing problems with it and I therefore gave up on it and now use this: [ https://github.com/ngoduykhanh/PowerDNS-Admin | https://github.com/ngoduykhanh/PowerDNS-Admin ] 

I think you'll find that relatively easy to get running and a helpful bunch of people maintaining it, from my point of view it's also about the best interface around for PowerDNS. 

Regards 

Bill

**Comment by edmondas** [comment]
It is difficult to maintain an open source project and face other life issues, but I want to announce the release of a new version. I know most of the updates have been collected over the previous 8 years. Also, I understand that there are better solutions with a nicer user interface. Currently, I am trying to restart development of the project and exploring available options for improving the UI (for example, InertiaJS and Tailwind's UI components look great).

By the way, if you are interested in discussing other topics, please use GitHub discussions.
