### ISSUE TITLE
when i add a wrong ipv4

### ISSUE THREAD

**Issue by tuvok81** [poweradmin/poweradmin#493]
![grafik](https://user-images.githubusercontent.com/30367063/216704709-87f0d2c3-55c9-413f-8b45-8431ea27353a.png)

can you add here a "back" button?

**Comment by tuvok81** [comment]
Or not a new window a "popup" was better i think? than we can close this popup and can work again

**Comment by edmondas** [comment]
The popup window is complicated because most of the code still uses server-side rendering and there's no API for it yet. I made modifications so that the form with the content remains visible even after an error occurs.

![image](https://user-images.githubusercontent.com/9033112/217160893-93af738d-9061-4685-a408-966dd0c97809.png)

**Comment by tuvok81** [comment]
ok :)
