### ISSUE TITLE
FEATURE DOC - Make more clear how to upgrade 

### ISSUE THREAD

**Issue by buzzzo** [poweradmin/poweradmin#497]
Coming from  old installations is not clear how to upgrade to the latest version.
In particular: documentation states "Update database structure (if needed)" BUT I've  not found in source any reference on how to update database structure, nor in various releases, in paritcular from 2.1.x to 3.x.

**Comment by edmondas** [comment]
You can also find some information in the wiki under the release notes section.
https://github.com/poweradmin/poweradmin/wiki

Otherwise, I try to include all significant information in the release. Maybe I should rethink how to keep such changelogs, especially for databases, but recent versions don't seem to have had any changes to databases. With the exception of maybe the experimental feature of logging to a database.

**Comment by buzzzo** [comment]
Thx for response.

Just to be more pratical: in order to upgrade from 2.1.7 to the latest 3.x branch would be sufficient to copy the new source file in place of the older 2.1.7 one AND keep the db of 2.1.7 ?

**Comment by edmondas** [comment]
It would be a smart idea to backup old files and databases, check the php extensions list to see if all of them are installed (for example, intl), add files from the latest release, and restore old configuration. There are some sql scripts in the SQL folder, and at least one of them related to the 2.2.1 release should be applied.

**Comment by edmondas** [comment]
@buzzzo Was the upgrade successful? Do you have any feedback?

**Comment by buzzzo** [comment]
Yes ,by simply dropping new sources and place the old config I was able to show the DNS info in the new UI (which is btw a huge improvement vs the old one).

No migration script was needed (which has failed in applying new changes to the dB).

So in the end I would assume that upgrade was successful.

Thx for help .

**Comment by edmondas** [comment]
I am closing this ticket since the main topic has been clarified.
