### ISSUE TITLE
suggestions for improvement

### ISSUE THREAD

**Issue by tuvok81** [poweradmin/poweradmin#502]
Hello,

1. is this Possible to make the "Theme" spark and the other to the Webinterface? for change? 
    $iface_style = 'spark'; // For dark themes, use 'spark'

2. on "Zone lists" 
![grafik](https://user-images.githubusercontent.com/30367063/229081220-3acaed96-0b0f-42eb-95d2-446084c311e4.png)
the "Show All" Button in German Language is "zeige Alle" or Alle anzeigen"

3. is this also possible to make the Language change also on Webinterface for change?
   $iface_lang = 'de_DE';

4. a Update via Webinterface was also nice

thank you for your good work!

**Comment by edmondas** [comment]
1. As part of the next release, I added a theme switcher to the UI (at the bottom, right corner. Cookie will be used to store the selected theme (dark or light), otherwise it will use the one defined in system configuration.
![image](https://user-images.githubusercontent.com/9033112/230966318-47b28604-21e6-460b-bfa7-9b58fba42296.png)

2. The list of letters was localized incorrectly, due to a bug. The next version will fix it.
3. There is now a possibility in the login screen, so I'm not sure what should be changed.
4. It sounds nice, but it's not easy and could bring different issues and require additional maintenance. I'll consider it, created a separate ticket for it #506, but I can't guarantee it'll be in the system anytime soon.
