### ISSUE TITLE
The Latest Version still have bugs

### ISSUE THREAD

**Issue by 4ndyhidayat** [poweradmin/poweradmin#503]
After a long day since yesterday, i thought my configuration is wrong. But it seems v3.5.0 still have bugs. The world can not recognize my NS using this version. But when i change into v3.4.2, everything went well. Here are my details installation: 

OS : FreeBSD 13.2-STABLE
Apache, Mariadb 106 (clusterdb), php81
VM : 1core, 1gb ram, 20gb hdd

Warm Regards,
Andy "m1m1n"
andy070609@gmail.com

**Comment by edmondas** [comment]
From the bug description, it's not clear what the problem really is, since NS records are just items in the database, perhaps there's something specific to PowerDNS, which you did not write. Based on the ports information, I expected it to be 4.7.3. Did you try dig for NS records? Did you see any errors in PowerDNS logs?

**Comment by 4ndyhidayat** [comment]
Yess, corect. I did not see anything in the log, i try to look up again
later.

**Comment by edmondas** [comment]
Could you please be more specific about the issue you had. Did it happen with a newly created zone? Check the output of `pdnsutil check-zone ZONE` to see what could be wrong from the PowerDNS perspective.

**Comment by 4ndyhidayat** [comment]
I'll let you know ASAP

**Comment by edmondas** [comment]
I am closing this since no response has been received. If the problem persists, please reopen this issue.
