### ISSUE TITLE
Additional features - possibly under contract?

### ISSUE THREAD

**Issue by iram-computer** [poweradmin/poweradmin#584]
Hello, 

Not sure where else to post, but we have been happily using poweradmin for some months now, and there are a few things that are missing and that would make it from good to great in our opinion:

- possibility to create the reverse record from a PTR zone (instead of only from a regular domain as it is now)
- possibility to column sort Disabled records
- last but not least, possibility to add comments for records and zones. When dealing with many zones, having a few words / lines to describe a specific zone would help a lot.

My company would consider paying for those (small-enough?) additional developments that may benefit others eventually. The only catch is that donations sadly are not supported, so we'll need to establish a quote and a contract.

I saw that you have been quite busy in the past year or so, but also that new updates are here. Hopefully something can be arranged.

**Comment by edmondas** [comment]
@iram-computer Thanks for your feedback and for using this system. It makes me want to keep working on it. I'm doing my best to make it better, even though I don't have much time or donations to work with.

Regarding the features requested:
- I can add the ability to make a reverse record from a PTR zone. However, this might take me some time to implement. The timeline depends on various factors, especially some older parts of the code that I'll need to work with.
- I added a basic option to sort by the disabled field. It's now available, but only in the master branch. However, I've noticed it only works one way. I need to rework the whole sorting system to allow both ascending and descending order.
- The zones already have a comments field, but it's not working well with PowerDNS. Our system uses a different table for storing comments than PowerDNS does. This difference in table usage needs to be resolved. As for record comments, I need to look into the different ways we could add this feature.

Thank you for your interest. While I cannot provide firm deadlines due to various personal commitments, I expect to implement these features within the next quarter. You're correct that I've been quite busy, but I continue to work hard on improvements. Regarding potential compensation and contract details, please feel free to contact me directly via the email address listed in my profile.

**Comment by edmondas** [comment]
All the requested features were implemented and tested to the extent possible. Any additional improvements or discovered issues should be addressed in separate tickets.
