### ISSUE TITLE
Sqlite3 uncaught exception readonly database.

### ISSUE THREAD

**Issue by DaanSelen** [poweradmin/poweradmin#602]
Hello, I love PowerAdmin! And I admire your work.

However, selecting Sqlite3 on the installation guide gives me a couple uncaught errors:

```
Updating database... Unable to connect to the database server. SQLSTATE[HY000] [14] unable to open database file
```

When manually creating the SQlite3 database. 

```
Updating database...
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in /var/www/html/lib/Infrastructure/Database/PDOLayer.php:211 Stack trace: #0 /var/www/html/lib/Infrastructure/Database/PDOLayer.php(211): PDO->exec() #1 /var/www/html/install/helpers/DatabaseHelper.php(60): Poweradmin\Infrastructure\Database\PDOLayer->createTable() #2 /var/www/html/install/helpers/InstallStepHandler.php(116): PoweradminInstall\DatabaseHelper->updateDatabase() #3 /var/www/html/install/helpers/Installer.php(97): PoweradminInstall\InstallStepHandler->step4SetupAccountAndNameServers() #4 /var/www/html/install/helpers/Installer.php(78): PoweradminInstall\Installer->handleStep() #5 /var/www/html/install/index.php(34): PoweradminInstall\Installer->initialize() #6 {main} thrown in /var/www/html/lib/Infrastructure/Database/PDOLayer.php on line 211
```

How do I use this?

**Comment by edmondas** [comment]
It seems the process trying to access the SQLite file doesn't have write access. This typically happens when your web server (like Apache or Nginx) runs under a different user than the file owner (like pdns service). Here are a few ways to fix this:

Option 1: Check current permissions and ownership first:
```bash
ls -l /path/to/database.sqlite
```

Option 2: Make it writable for all processes (less secure, only for testing):
```bash
chmod 666 /path/to/database.sqlite
```

Option 3 (Recommended): Add the web server user to the file's group:
```bash
# For Apache (assuming www-data is the web server user)
usermod -a -G pdns www-data
# Update file permissions
chown pdns:pdns /path/to/database.sqlite
chmod 660 /path/to/database.sqlite
```

Important security note: Never put the SQLite file in a publicly accessible location like public_html. Instead, store it in a secure location. After making these changes, remember to restart your web server:
```bash
systemctl restart apache2  # For Apache
# or
systemctl restart nginx   # For Nginx
```

These are just initial suggestions - the exact solution will depend on your specific system configuration, security requirements, and server setup.

**Comment by DaanSelen** [comment]
> It seems the process trying to access the SQLite file doesn't have write access. This typically happens when your web server (like Apache or Nginx) runs under a different user than the file owner (like pdns service). Here are a few ways to fix this:
> 
> Option 1: Check current permissions and ownership first:
> 
> ```shell
> ls -l /path/to/database.sqlite
> ```
> 
> Option 2: Make it writable for all processes (less secure, only for testing):
> 
> ```shell
> chmod 666 /path/to/database.sqlite
> ```
> 
> Option 3 (Recommended): Add the web server user to the file's group:
> 
> ```shell
> # For Apache (assuming www-data is the web server user)
> usermod -a -G pdns www-data
> # Update file permissions
> chown pdns:pdns /path/to/database.sqlite
> chmod 660 /path/to/database.sqlite
> ```
> 
> Important security note: Never put the SQLite file in a publicly accessible location like public_html. Instead, store it in a secure location. After making these changes, remember to restart your web server:
> 
> ```shell
> systemctl restart apache2  # For Apache
> # or
> systemctl restart nginx   # For Nginx
> ```
> 
> These are just initial suggestions - the exact solution will depend on your specific system configuration, security requirements, and server setup.

Thank you for your response, I tried `chmod 777` on the .db/.sqlite file, but to no avail. I can try another user, will update with my findings soon (probably tomorrow)

**Comment by edmondas** [comment]
Please check if all the folders in the path where the db is stored are accessible to the web server user, if that .db has permissions only of 700 and belongs to another user & group, then of course the web user won't be able to access that file due to lack of permissions.

**Comment by muzzol** [comment]
sorry to resurface this but I was facing this problem and I tried with giving write access to group www-data and it didn't work. but it worked when I changed the order of owner and group.

```
-rw-rw-r--  1 www-data pdns     73728 Jan 15 10:40 pdns.sqlite3
-rw-rw-r--  1 pdns     www-data 73728 Jan 15 10:40 pdns.sqlite3.not-working
```

not sure how installer checks this but second one should work too and now it's not.

**Comment by DaanSelen** [comment]
> sorry to resurface this but I was facing this problem and I tried with giving write access to group www-data and it didn't work. but it worked when I changed the order of owner and group.
> 
> ```
> -rw-rw-r--  1 www-data pdns     73728 Jan 15 10:40 pdns.sqlite3
> -rw-rw-r--  1 pdns     www-data 73728 Jan 15 10:40 pdns.sqlite3.not-working
> ```
> 
> not sure how installer checks this but second one should work too and now it's not.

Interesting...

**Comment by muzzol** [comment]
maybe it could be related to the permissions of the directory instead of the file.
does the installer removes/creates a new file?

**Comment by serossi** [comment]
i necro this as i stumbled into this and cant find any recommended way to solve it in the documentation

issue is the moment pdns start it will create -shm and -wal files as user/group pdns:pdns

options to solve this are either
-turn of wal 
-run apache as user pdns
-adjust group rights after pdns started via script/systemd
-add www-data to the group dns

since i run it only as an internal setup i opted for adding it to the group

**Comment by edmondas** [comment]
@serossi Yes, the best approach in this case would be to add www-data to the pdns group.
